# Generated by Django 4.0.2 on 2022-02-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feature',
        ),
    ]
